# environment settings
seed: 0
precision: fp32 #bf16
strategy: ddp

# data arguments
dataset: davis2017
num_workers: 1
global_batch_size: 16
max_channels: 1  
shot: 8
eval_batch_size: 16
n_eval_batches: -1
img_size: 128 #224
image_augmentation: False # Horizontal Flip
support_idx: 0
channel_idx: -1
use_valid: True 
# class_name: breakdance

sample_by_seq: True
sample_skip: 25

# model arguments
semseg_threshold: 0.2
attn_dropout: 0.5
# time_attn: 0 # time_attn < 2 only space attention (VTM base model) 

# training arguments
n_steps: 1000 #20000
n_schedule_steps: 20000
optimizer: adam
lr: 0.005
lr_pretrained: 0.0002
lr_schedule: constant 
lr_warmup: 0
lr_warmup_scale: 0.
schedule_from: 0
weight_decay: 0.
lr_decay_degree: 0.9
mask_value: -1.
early_stopping_patience: 100 #5
interaction_drop: 0
bitfit_init: avg 
multimodal_softmax_loss: False
multimodal_mse_loss: False
temp_msl: 1.0
dynamic_support: False
dynamic_support_interval: 2
average_real_bias_only: False
l2b_freeze_bias: False
permute_classes: False
patches_per_img: 9
additional_bias: False

bitfit: True 
qkv_bitfit: True  
time_attn: 0 # time_attn < 2 only space attention (VTM base model) 
pretrained_vtm: True
# logging arguments
class_name: bmx-trees
log_dir: FINETUNE/DAVIS-128/PRETASKO-224-MIDAIR-128-samp2/s-meta8-shot8-n16
save_dir: FINETUNE/DAVIS-128/PRETASKO-224-MIDAIR-128-samp2/s-meta8-shot8-n16
load_dir: TRAIN/PRETASKO-224-MIDAIR-128-samp2/s-meta8
# load_dir: TRAIN-BASE/taskonomy-fold4

load_dir_aux: DOMAIN_ADAPTATION
val_iter: 100
load_step: -1

# dog, horsejump-high, paragliding-launch, bmx-trees