# environment settings
seed: 0
precision: fp16 #bf16
strategy: ddp

# data arguments
dataset: kittiflow
test_split: test
num_workers: 1
shot: 10
eval_batch_size: 8
n_eval_batches: -1
img_size: 224
support_idx: 0
channel_idx: -1

sample_by_seq: True
sample_skip: 8

# model arguments
semseg_threshold: 0.2
dynamic_support: False
dense_crf: False

# logging arguments
log_dir: TEST
load_dir_aux: DOMAIN_ADAPTATION
save_dir: FINETUNE
load_dir: TRAIN
load_step: 0
